version: 0.0 
os: linux

files: 
  - source: /
    destination: /root/KGflex

permissions: 
  - object: scripts
    pattern: "**"
    owner: root 
    group: root 
    mode: 755
    type: 
      - file
  - object: /root/KGflex/scripts
    pattern: "**"
    owner: root 
    group: root 
    mode: 755
    type: 
      - file
hooks: 
  BeforeInstall: 
  - location: /scripts/before_update.sh
    timeout: 30
    runas: root 
  AfterInstall: 
  - location: /scripts/update_project.sh
    timeout: 300
    runas: root 
  ValidateService: 
  - location: /scripts/validation.sh
    timeout: 30
    runas : codedeployuser
