# Generated by Django 3.1 on 2022-08-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KGflex', '0005_kdrama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdrama',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='KGflex/KDrama/'),
        ),
        migrations.CreateModel(
            name='KDDrama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('file_upload', models.FileField(blank=True, upload_to='KGflex/KDrama/')),
                ('photo_thumbnail', models.ImageField(upload_to='blog/post')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
