# Generated by Django 3.1 on 2022-08-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KGflex', '0006_auto_20220819_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdrama',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, upload_to='blog/post'),
        ),
        migrations.DeleteModel(
            name='KDDrama',
        ),
    ]
