# Generated by Django 3.1 on 2022-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KGflex', '0007_auto_20220819_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdrama',
            name='photo_thumbnail',
            field=models.ImageField(upload_to='blog/post'),
        ),
    ]
