# Generated by Django 3.1 on 2022-08-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KGflex', '0008_auto_20220819_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kdrama',
            old_name='photo_thumbnail',
            new_name='photo',
        ),
    ]
