# Generated by Django 3.1 on 2022-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KGflex', '0009_auto_20220819_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdrama',
            name='file_upload',
            field=models.FileField(upload_to='KGflex/KDrama/'),
        ),
    ]
