# Generated by Django 3.1 on 2022-08-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KGflex', '0019_auto_20220819_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='kdrama',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='kdrama',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='kdrama',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='kmovie',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='kmovie',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='kmovie',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='umovie',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='umovie',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='umovie',
            name='content3',
        ),
    ]
